unplugin/unplugin-icons

- client.d.ts
The module declaration for the legacy virtual file imports (`declare module '/@vite-icons/*' {`) was causing Typescript to throw errors in some circumstances.
As it seems vite has now settled on the `virtual:...` convention instead, this declaration would only be for backwards compatibility, so I don't think it's necessary.
Removing this declaration resolves #25.
> fix: remove ambient type declaration for virtual imports using `/@vite...` syntax

- types/solid.d.ts
the previous type didn't support properties like onclick. This commit
fix it.
> fix: types for solid

- README.md
- examples/vite-svelte/vite.config.js
This PR also fixes the `vite-svelte` example: the `vite.config.ts` file should be `vite.config.js`.
> docs: add svelte entries

- package.json
On root `package.json` scripts, the run/build `vite-vue3` scripts point to `vue3` directory instead `vite-vue3`.
Running the `example:dev` script, `vue3` just works.
> chore: run/build `vite-vue3` example scripts uses wrong directory

- README.md
- examples/vite-vue3/App.vue
- examples/vite-vue3/components.d.ts
- examples/vite-vue3/vite.config.ts
- src/resolver.ts
Can also be used the long way: `<i-park-abnormal />` and `<i-icon-park-abnormal />`.
Only added one example on `vite-vue3`.
closes #39
> feat: add component resolver aliases

- examples/sveltekit/src/routes/index.svelte
- examples/vite-svelte/src/App.svelte
- src/core/compilers/index.ts
- src/core/compilers/svelte.ts
- src/core/utils.ts
This PR adds a new compiler to allow passing props to the component:
- changed `compilers` to use this new `SvelteCompiler` instead `NoneCompiler`: it has been optimized to use [`{@html }`](https://svelte.dev/tutorial/html-tags) on svg content.
- added `escapeSvelte` utility function
- added style on svelte logo on `vite-svelte` and `svelte-kit` example projects.
> feat: add svelte compiler for props support

- types/react.d.ts
- types/svelte.d.ts
This PR also includes: 
- use single quotes on svelte types
The types seems to be ok with changes proposed on the issue, IntelliJ resolves also attrs:
fix #78
> fix: react types

- src/core/compilers/marko.ts
- src/core/compilers/svelte.ts
> fix: remove extra `>` char on svelte and marko compilers

- src/core/compilers/vue2.ts
- src/core/compilers/vue3.ts
Instead using `dynamic import` now we use `importModule` from `local-pkg`  also on `vue2` and `vue3` compilers.
@antfu Review the `vue2` compiler changes since I cannot test on my local.
closes #120
> feat: use `importModule` instead `dynamic import`

- src/index.ts
Should fallback to return original `res` when user didn't provide compiler option.
> fix: resolve icons id without compiler option

- src/core/compilers/jsx.ts
This PR checks for `transform` for `v6`, `default` for `v5` and the module itself for previous versions.
/cc @dominikg for your svelte preprocessor
closes #96
> fix(compiler-jsx): check for multiple svgr version

- README.md
The new version is `v0.13.0` not `v0.12.24`, updating `from` references.
Also updates query param code snippet, should be width and height.
> docs: update new features version

- README.md
- examples/sveltekit/src/routes/index.svelte
- examples/sveltekit/svelte.config.js
- examples/vite-preact/src/app.tsx
- examples/vite-react/src/App.tsx
- examples/vite-svelte/src/App.svelte
- examples/vite-vue3/App.vue
- src/core/loader.ts
- src/core/utils.ts
- src/index.ts
Since there is only one compiler, we cannot use `raw` compiler when necessary, this PR will allow use `raw` in query param to use the svg on the html/sfc.
Included example on `vite-vue3` example, see screenshot on #151.
closes #151
closes #165
> feat: allow use raw compiler from query params

- src/core/compilers/vue3.ts
fix: 
```js
`import { createElementVNode as _createElementVNode, openBlock as _openBlock, createElementBlock as _createElementBlock } from "vue"
const _hoisted_1 = { viewBox: "0 0 24 24" }
const _hoisted_2 = /*#__PURE__*/_createElementVNode("path", {
fill: "currentColor",
d: "M6 17c0-2 4-3.1 6-3.1s6 1.1 6 3.1v1H6m9-9a3 3 0 0 1-3 3 3 3 0 0 1-3-3 3 3 0 0 1 3-3 3 3 0 0 1 3 3M3 5v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2Z"
}, null, -1 /* HOISTED */)
const _hoisted_3 = [
_hoisted_2
]
export function render(_ctx, _cache) {
return (_openBlock(), _createElementBlock("svg", _hoisted_1, _hoisted_3))
}`.replace(/^export /g, '')
```
> fix(compiler-vue3): RegExp miss multiline flag for clean export

- src/core/compilers/vue2.ts
It's a backported https://github.com/antfu/unplugin-icons/commit/0908f60074053e231eafba4fe02a4791b2bcc333 to vue2 compiler. Fixes #188.
> fix: duplicate svg id in vue2 compiler

- README.md
I noticed the `unplugin-components` import in the `README.md` does not have any relevant npm package, I assumed it should have been the `unplugin-vue-components`.
> docs: correct unplugin-vue-components import

- README.md
> Fix typo in documentation (“convension”)

- README.md
- examples/nuxt3/nuxt.config.ts
- examples/nuxt3/package.json
- src/nuxt.ts
Adds support with backward compatibility for the new Nuxt 3.0.0 stable release.
fixes #249 
Since there is no test regarding this feature currently and it requires different versions of Nuxt installed to validate, so I manually tested via `examples/nuxt3`.
* The example using `nuxt@3.0.0-rc.12` runs correctly before my change.
* The example using `nuxt@3.0.0` failed to run without my change.
`Cannot read properties of undefined (reading 'nuxt')`
* The example using `nuxt@3.0.0` runs correctly with my change.
* The example using `nuxt@3.0.0-rc.12` runs correctly after my change. (backward compatible)
> fix: nuxt 3.0.0 stable support

- package.json
Adds @vue/compiler-sfc 2.7 compiler as a valid option.
Currently following documentation to install unplugin-icons on vue 2.7 project and using automatic component resolution will add @vue/compiler-sfc as a dev dependency to the project.
However if project is created or installed from zero, npm install will fail as peer-dependency of the project request for @vue/compiler-sfc is 3+ as such.
This PR aims to add @vue/compiler-sfc 2.7 version as a optional peer dependency to allow clean installations of the library.
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: unplugin-icons@0.15.0
npm ERR! Found: @vue/compiler-sfc@2.7.14
npm ERR! node_modules/@vue/compiler-sfc
npm ERR!   dev @vue/compiler-sfc@"^2.7.7" from the root project
npm ERR! …
```
> fix: update @vue/compiler-sfc peer dependency to support Vue 2.7

- README.md
Since version [7.0.0](https://github.com/gregberge/svgr/releases/tag/v7.0.0) `@srvg/plugin-jsx` is not part of `@svgr/core` and have to be installed separately.
https://github.com/antfu/unplugin-icons/issues/275
https://github.com/antfu/unplugin-icons/pull/276
This has been fixed in the PR above, but users still need to install that dependency on their own, therefore the README needs to be updated.
> docs: adds `@svgr/plugin-jsx` to React/Preact README

- README.md
- package.json
- pnpm-lock.yaml
- src/core/compilers/qwik.ts
- src/index.ts
Qwik support for `unplugin-icons` was working for a brief period but is no longer working. The example project in this repo does not display an icon, and simply has an empty `svg` tag in place of the icon. This PR fixes the Qwik integration and makes importing icons function as expected.
The root of this issue is that the existing compiler for Qwik was outputting pre-compiled Javascript (not JSX), but was reporting the file type as `tsx`. As a result, icons were being double processed, ultimately resulting in a broken component. This PR updates the Qwik compiler to output JSX, and allows the remaining transformations to be handled by the Qwik JSX compiler for better compatibility.
> fix: update qwik support

- src/core/compilers/solid.ts
Props replacement wasn't working because the lookbehind only included the symbol '.', which doesn't match newlines.
According to [the XML spec](https://www.w3.org/TR/2006/REC-xml11-20060816/#sec-starttags), newlines can be included in the spacing in a starttag.
This was a very quick fix, so I figured I did not need to create an issue
Input:
```xml
<svg
width="35"
height="44"
viewBox="0 0 35 44"
fill="currentColor"
xmlns="http://www.w3.org/2000/svg"
role="presentation"
>
</svg>
```
Output before fix:
```jsx
export default (props = {}) => <svg
width="35"
height="44"
viewBox="0 0 35 44"
fill="currentColor"
xmlns="http://www.w3.org/2000/svg"
role="presentation"
>
{/* (left out, irrelevant) */}
</svg>
```
Output after fix:
```jsx
export default (props = {}) => <svg
width="35"
height="44" …
```
> fix(compiler-solid): Props replacement not working with multiline starttags

- src/core/compilers/index.ts
- src/types.ts
This pr change:
- Partial of `transform` in `ResolvedOptions`
- Exclued `CustomCompiler` in `compilers`
#216
> fix(types): fix type errors

- README.md
This PR includes the breaking changes introduced in `v0.18.0` about CJS default exports:
- webpack
- Vue-CLI
- Next
> docs: update cjs usage in readme file

- examples/sveltekit/package.json
- examples/sveltekit/src/routes/+page.svelte
- examples/sveltekit/svelte.config.js
- pnpm-lock.yaml
- src/index.ts
When splitting the query params from the icon id there is an additional `?`, we must use `queryIndex + 1`.
This PR also updates to SvelteKit 2 the example and updates a raw icon to use width/height with `4.25em`.
closes #338
> fix: wrong query params splitting when resolving icon id

- README.md
- examples/vite-vue3/App.vue
- examples/vite-vue3/components.d.ts
- examples/vite-vue3/vite.config.ts
- package.json
- pnpm-lock.yaml
- src/loaders.ts
`@iconify/utils` from `v2.1.20` exposes a new `CustomIconLoader`  to allow load icons from custom external collection packages, this PR just adds the helper and the corresponding entry in the readme file.
@antfu should we  cleanup types and update TS to 5.3.3?
https://github.com/iconify/iconify/pull/276
> feat: custom external collection packages

- src/core/compilers/vue3.ts
Currently if someone imports and passes a icon component as prop, Vue will track it deeply and will give warnings regarding associated performance overhead. This PR wraps the exported element with `markRaw` to disable deep tracking.
> feat(vue3): allow passing components as props without reactivity overhead

- package.json
- pnpm-lock.yaml
#347 introduced support for Svelte 5 runes. In doing so, the Svelte plugin now imports from `svelte/compiler`. Without `svelte` being listed as an optional peer dependency, the import did not correctly resolve `svelte` from the current workspace within a monorepo. Thus, if another package in the monorepo depended on Svelte 5, a package depending on Svelte 4 could be misidentified as the newer version.
> fix: Svelte runes detection not working correctly in monorepos

- examples/next/next.config.js
We need to use `.default` when registering webpack plugin
This PR just updates the Next configuration file to use `.default` when registering the unplugin icons webpack plugin
NA
Modified example https://stackblitz.com/edit/unplugin-unplugin-icons-xrvbve?file=next.config.js,pages%2Findex.tsx
> chore: fix Next example configuration file

- src/core/compilers/jsx.ts
- types/react.d.ts
In my project, I want to pass a ref to the generated React component, but it doesn't do anything and I get this error in the browser console:
> Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
This PR enables SVGR's [`ref` option](https://react-svgr.com/docs/options/#ref) if we are using React, which forwards ref to the root SVG tag.
> feat(react): enable ref option for SVGR in JSX compiler

- README.md
This is just a small documentation change to note that the `@vue/compiler-sfc` peer dependency is no longer required as of Vue 3.12.13, and is now included with the main vue package.
> docs: updated README with note about Vue 3.12.13+ dropping requirement for `@vue/compiler-sfc` to be installed
