README.md

Added instruction to install peer dependency @iconify/json as a dev dependency to avoid this error #2

docs(README): install @iconify/json

---

client.d.ts
examples/vue3/App.vue
examples/vue3/vue-shim.d.ts
src/constants.ts
src/index.ts
src/loader.ts

declare module not support module name started with `/`

feat: support virtual prefix & add virtual module type

---

src/compiler/vue3.ts

Add a name property to the generated vue3 code for a better experience with Vue devtool.

feat: component name for vue3 code

---

src/core/compilers/vue2.ts
src/core/compilers/vue3.ts

This reverts commit 62866166a3c07a7612b584cd7c52e9f0bf26b91e.
Fixes #53

Revert "pref: use v-pre to improve pref"

---

examples/vite-react/vite.config.ts

docs: fix vite-react example

---

types/svelte.d.ts

fix: improve svelte component typing

---

package.json
pnpm-lock.yaml
src/core/utils.ts

fix: chalk on esm

---

examples/vite-svelte/package.json
examples/vite-svelte/src/CustomSvg.svelte
examples/vite-svelte/vite.config.js
src/core/compilers/types.ts
src/core/loader.ts
src/index.ts
src/types.ts

feat: custom compiler

---

README.md

docs: add svelte note to svelte + vite as well

---

package.json

copied-and-pasted from my local environment, not tested on this branch

fix: types not resolved in ts >=4.5, fix #119

---

README.md
examples/vite-vue3/App.vue
examples/vite-vue3/vite.config.ts
src/core/custom.ts
src/core/loader.ts
src/core/modern.ts
src/core/options.ts
src/core/utils.ts
src/types.ts

feat: add icon customizer

---

README.md

fix the type of `options.resolvers`

chore: update example

---

types/svelte.d.ts

Added SVGProps to svelte components

fix: add svg props to svelte components

---

README.md

sorry, mixed with the unocss preset icons

docs: move `@iconify/tools` section one level up

---

package.json

fix: fix default imports from subpath getting wrong type

---

package.json
pnpm-lock.yaml

Upgrade unplugin to 0.9.5
- https://github.com/unjs/unplugin/pull/155
- fix https://github.com/antfu/unplugin-icons/issues/231

chore(deps): bump unplugin to fix #231

---

README.md

That was the old way to configure it. We now put Vite config in `vite.config.js` instead of `svelte.config.js`

docs: update SvelteKit instructions

---

package.json
pnpm-lock.yaml

Updates Iconify Utils dependency
Fixes: https://github.com/iconify/iconify/issues/192

chore: update Iconify Utils

---

README.md
examples/vite-preact/package.json
package.json

chore: lint fix

---

package.json

chore: add typecheck cmd

---

examples/sveltekit/package.json
pnpm-lock.yaml

Just a minor thing I noticed while looking at the example

chore: upgrade sveltekit from beta version to final release

---

README.md

Fixes a broken/outdated link in the readme.

docs: framework contribute link

---

README.md

Include license link in readme footer.
NA

docs: include license link in readme

---

README.md

The first several times I came here I didn't realize there were examples as they weren't mentioned in the docs. I only noticed pretty recently. Adding some links should help make the examples more discoverable for other users

docs: add links to examples

---

README.md

Readme example link for Nuxt integration is not up to date, this PR fixes that
#306 - docs: add links to examples

docs: Update Nuxt example project link

---

examples/vite-svelte/src/App.svelte
examples/vite-vue3/App.vue
src/index.ts

Splits props from id and apply normalization only to the normalized id
closes #322

fix: resolve id when icon name includes `.` in icon props

---

README.md

Iconify now has ~150 icon sets and 200K+ icons:
https://iconify.design/news/2023.html#new-milestone

docs: update latest Iconify milestone

---

test/__snapshots__/idSvg.test.ts.snap

test: fix shapshot

---

package.json

Missing types in packages exports.
closes #349

fix(types): add qwik to package exports

---

src/core/compilers/vue2.ts

Fix a Vue2 compiler issue
closes https://github.com/unplugin/unplugin-icons/issues/355

fix: vue2 compiler issue

---

package.json
pnpm-lock.yaml

Upgrade to the latest `install-pkg`
There are currently multiple versions of `install-pkg` in the dependency tree. https://npmgraph.js.org/?q=unplugin-icons

chore: upgrade install-pkg

---

README.md

`vite.config.json` -> `vite.config.js`

fix(typo): replace `vite.config.json` with `vite.config.js`

---

package.json
src/rolldown.ts
tsdown.config.ts

This PR also simplifies all subpackages exports.

feat: add `rolldown`
